[profile.default]
src = "contracts"
test = 'test'
out = "out"
libs = ["lib"]

solc = "0.8.28"
optimizer = true
optimizer_runs = 100000
via_ir = true
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
